### ISSUE TITLE
X11/Intrinsic.h: No such file or dictory

### ISSUE THREAD

**Issue by Vital-Fernandez** [iraf-community/x11iraf#38] opened 2021-01-24 01:35 UTC
I wonder if anyone could advice me on this issue: 

I am installing x11iraf (and iraf) on an ubuntu 20.04 virtual machine (this one is on windows 10)

The instructions are very clear and I managed to install the dependencies and iraf without issues. But I am getting this error once I build with build:

```
make -C obm
make[1]: Entering directory '/home/vital/x11iraf-2.0-2020.06.15/obm'
/home/vital/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/vital/anaconda3/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/vital/anaconda3/include  -c -o Obm.o Obm.c
In file included from Obm.c:5:0:
ObmP.h:16:10: fatal error: X11/Intrinsic.h: No such file or directory
 #include <X11/Intrinsic.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: Obm.o] Error 1
make[1]: Leaving directory '/home/vital/x11iraf-2.0-2020.06.15/obm'
make: *** [Makefile:8: obm/libobm.a] Error 2
```

Thank you for any advice

**Comment by olebole** [comment] 2021-01-24 10:27
You should try to install `libxt-dev`, which gives a file `/usr/include/X11/Intrinsic.h`. I am however wondering why it is not installed as it is a depedency of `libxmu-dev`. Can you check this?

**Comment by Vital-Fernandez** [comment] 2021-01-25 01:40
Thank you very much. I have removed the anaconda compiler, reinstalled the dependencies and deleted the folders with the revious installation to start again.

Now however, once I ran the ./install for the iraf installation the terminal gets stuck with the following messages:

./install: 305: NEWLINE: not found
./install: 306: BOLD_ON: not found
./install: 307: ECHO: not found
./install: 308: ECHO: not found
./install: 309: ECHO: not found
./install: 310: BOLD_OFF: not found
./install: 311: NEWLINE: not found
./install: 313: ECHO: not found

Any advice on this issue? Sorry for all the trouble.

**Comment by olebole** [comment] 2021-01-25 08:26
I would really recommend not to start with IRAF if you are a newcomer. IRAF is really outdated and reached its end of life. Instead, consider using [Astropy](https://astropy.org), and its affiliated packages, which are capable to solve most of the problems that IRAF was made for. Efforts should go into improving Astropy packages instead of trying to step into IRAF.

For the IRAF problem, the cause is probably that you have defined the `$iraf` environment variable, which points to some other IRAF installation (from astroconda?). This, and all other environment variables for IRAF (like `$host`) should be removed, as well as additions to your PATH which prefer using tools from this other IRAF installation.
But why don't you just install the iraf package that comes with Ubuntu?

Since the x11iraf problem seems to be solved, I am closing this issue.

**Closed by olebole** 2021-01-25 08:26 UTC
